name: Build image and push to DockerHub

on:
  # Allow manual trigger
  workflow_dispatch:

jobs:
  build-image-and-push:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      # If you go to
      # https://blog.pamelafox.org/2023/03/deploying-containerized-fastapi-app-to.html ,
      # you will find some basic but also helpful information about `docker buildx`.
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build container image and push it to DockerHub repository
        uses: docker/build-push-action@v4
        with:
          push: true
          context: .
          tags: kaloyanmarinov/msdocs-python-flask-azure-container-apps-3:${{ github.sha }}
